baseURL = "https://gurleen.dev/"
languageCode = "en-us"
title = "Gurleen Singh"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#6ecd9f"
    description = "Portfolio of Gurleen Singh, CS Student"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "gurleen.singh@drexel.edu"
    # facebook = "lex.collado"
    # dribbble = "alexiscollado"
    linkedin = "https://www.linkedin.com/in/gsingh2000/"
    # medium = "ahvccollado"
    github = "gurleen"
    # googlescholar = "https://scholar.google.com/citations?user=XXXXXXXXXXXXXXXXXXXXX=en"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.png"
    subtitle = "Hi! I'm Gurleen, a CS student from Philadelphia."
    hero_right = ["I most recently was an Associate SWE in Baseball R&D at the [Philadelphia Phillies](https://phillies.com).", 
                 "Before that, I was a Software Development Co-op for [Susuqehanna International Group](https://sig.com/), a trading firm in Bala Cynwyd, PA. There, I supported the Energy trading desk by building software for market data delivery.", 
                 "I was also a software engineering intern at [Linode](https://linode.com/), the world's largest independent cloud provider. I worked on Linode APIv4, providing a world-class experience for customers and developers.",
                 "I'm finishing my Bachelor's degree in Computer Science at Drexel University's College of Computing and Informatics, expecting to graduate in 2023. I have a minor in Sports Management.",
                 "Outside of class, I produce TV broadcasts for the [Drexel Dragons](https://drexeldragons.com/) on NBC Sports Philadelphia.",
                 "I'm also big fan of Philly sports. Go Birds! 🦅"
                 ]
    resume = "Gurleen Singh Resume.pdf"

[params.process]
    enable = false
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = false
    title = "Case Studies"
    subtitle = "Selected Works"

[params.footer]
    enable = false
